#############
# Templates #
#############

.common:
  only:
    refs:
      - master
      - merge_requests
  except:
    refs:
      - schedules

.nightly:
  only:
    refs:
      - schedules
    variables:
      - $LIBRISTRA_SCHEDULE == "nightly"
  except:

.cache:
  cache:
    #key: ${CI_JOB_NAME_NOSTAGE%.*}-${CI_COMMIT_REF_SLUG}
    key: ${CI_COMMIT_REF_SLUG}-${CI_JOB_NAME}
    paths:
      - ${CCACHE_DIR}

.artifacts:
  artifacts:
    name: "libristra-${CI_COMMIT_REF_SLUG}-${CI_JOB_NAME}-${CI_JOB_ID}"
    paths:
      - ${CI_PROJECT_DIR}/build #/builds/next-generation-codes/laristra/flecsale-mm/build
    when: always
    expire_in: 1 hour
  dependencies: []

.batch_runner:
  tags:
    - darwin-slurm-shared
  variables:
    SCHEDULER_PARAMETERS: "--nodes=1 --partition=skylake-gold"

.job:
  retry: 0
  extends:
    - .common
    - .cache
    - .batch_runner

.update_spackage:
  script:
    - echo 'Updating spackages...'
    - cd ${CI_PROJECT_DIR}
    - for f in $(find ./spack-repo/packages/ -type f); do diff -urN ${CI_PROJECT_DIR}/ristra_spackages/$f $f | tee $f.patch || /bin/true; done
    - for f in $(find ./spack-repo/packages/ -type f -name "*.patch"); do patch -i $f ${CI_PROJECT_DIR}/ristra_spackages/${f%.*}; done
    - for f in $(find ./spack-repo/packages/ -type f -name "*.patch"); do rm $f; done
    - cd ${CI_PROJECT_DIR}/ristra_spackages
    - git add spack-repo/packages/*
    - git commit -m "Gitlab CI Automatic Spackage Update - Libristra" || /bin/true
    - git push -u origin master

