#############
# Templates #
#############

.common:
  only:
    refs:
      - master
      - merge_requests
  except:
    refs:
      - schedules

.nightly:
  only:
    refs:
      - schedules
    variables:
      - $LIBRISTRA_SCHEDULE == "nightly"
  except:

.cache:
  cache:
    #key: ${CI_JOB_NAME_NOSTAGE%.*}-${CI_COMMIT_REF_SLUG}
    key: ${CI_COMMIT_REF_SLUG}-${CI_JOB_NAME}
    paths:
      - ${CCACHE_DIR}

.artifacts:
  artifacts:
    name: "libristra-${CI_COMMIT_REF_SLUG}-${CI_JOB_NAME}-${CI_JOB_ID}"
    paths:
      - ${CI_PROJECT_DIR}/build #/builds/next-generation-codes/laristra/flecsale-mm/build
    when: always
    expire_in: 1 hour
  dependencies: []

.batch_runner:
  tags:
    - darwin-slurm-shared
  variables:
    SCHEDULER_PARAMETERS: "--nodes=1 --partition=skylake-ci-ristra,skylake-gold"

.job:
  retry: 0
  extends:
    - .common
    - .cache
    - .batch_runner

