flecsale-mm:
  stage: "Trigger"
  only:
    - merge_requests
    - master
  variables:
    UPSTREAM_REPO: "ristra"
    UPSTREAM_BRANCH: $CI_COMMIT_REF_NAME
    UPSTREAM_URL: $CI_REPOSITORY_URL
  trigger:
    project: laristra/flecsale-mm
    branch: master
    strategy: depend

