#!/bin/bash

export COMPILER='pgc++ -std=c++14
   -I../src
   -w'

for file in *.cc
do
   echo "Compiling" ${file} "to" ${file/.cc/}
   $COMPILER ${file} -o ${file/.cc/}
   echo "Comparing" ${file} "w/" ${file/.cc/}.blessed
   ./${file/.cc/} | diff ${file/.cc/}.blessed -
done
