#!/bin/bash

export COMPILER='g++ -std=gnu++14
   -Wall -Winit-self -Wmissing-include-dirs -Wswitch-default -Wswitch-enum
   -Wstrict-aliasing=2 -Wundef -Wextra -Wpointer-arith -Wunused-parameter
   -Wcast-align -Wwrite-strings -Wredundant-decls -Wcast-qual -Wno-sign-compare
   -I../src
   -pthread -pedantic -latomic -O3'

echo
for file in *.cc
do
   echo "build" ${file} "to" ${file/.cc/}
   $COMPILER ${file} -o ${file/.cc/}
   if [ -e ${file/.cc/}.blessed ]
   then
      echo "compare" ${file/.cc/} "output to" ${file/.cc/}.blessed
      ./${file/.cc/} | diff ${file/.cc/}.blessed -
   else
      echo "run" ${file/.cc/}
      ./${file/.cc/}
   fi
   echo
done
