#!/bin/bash

export COMPILER='pgc++ -std=c++14
   -I../src
   -w -latomic'

echo
for file in *.cc
do
   echo "build" ${file} "to" ${file/.cc/}
   $COMPILER ${file} -o ${file/.cc/}
   if [ -e ${file/.cc/}.blessed ]
   then
      echo "compare" ${file/.cc/} "output to" ${file/.cc/}.blessed
      ./${file/.cc/} | diff ${file/.cc/}.blessed -
   else
      echo "run" ${file/.cc/}
      ./${file/.cc/}
   fi
   echo
done
