#!/bin/bash

export COMPILER='pgc++ -std=c++14
   -I../src
   -w'

# For now, exclude *.cc files that need threads.
# Those have linking problems with pgc++.
for file in [^m]*.cc
do
   echo "Compiling" ${file} "to" ${file/.cc/}
   $COMPILER ${file} -o ${file/.cc/}
done
